/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import com.alee.laf.WebLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author ACER
 */
public class Halamanutama extends javax.swing.JFrame {

    /**
     * Creates new form Halamanutama
     */
    public Halamanutama() {
        initComponents();
        
//        addComp(new TambahDokter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelInduk = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miDataDokter = new javax.swing.JMenuItem();
        miDataPasien = new javax.swing.JMenuItem();
        miRekamMedis = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rekam Medis");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(745, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(745, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        PanelInduk.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelInduk, java.awt.BorderLayout.CENTER);

        mFile.setText("File");

        miDataDokter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        miDataDokter.setText("Data Dokter");
        miDataDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDataDokterActionPerformed(evt);
            }
        });
        mFile.add(miDataDokter);

        miDataPasien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miDataPasien.setText("Data Pasien");
        mFile.add(miDataPasien);

        miRekamMedis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        miRekamMedis.setText("Data Rekam Medis");
        mFile.add(miRekamMedis);
        mFile.add(jSeparator1);

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miLogout.setText("Logout");
        mFile.add(miLogout);

        jMenuBar1.add(mFile);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDataDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDataDokterActionPerformed
        // TODO add your handling code here:
        addComp(new DataDokter());
    }//GEN-LAST:event_miDataDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (Exception e) {
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            //                new Halamanutama().setVisible(true);
            Halamanutama L = new Halamanutama();
            L.setExtendedState(Frame.MAXIMIZED_BOTH);
            L.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel PanelInduk;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miDataDokter;
    private javax.swing.JMenuItem miDataPasien;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miRekamMedis;
    // End of variables declaration//GEN-END:variables

    public static void addComp(JPanel panel) {
        if (PanelInduk.getComponentCount() > 0) {
            PanelInduk.removeAll();
        }
        PanelInduk.add(panel, BorderLayout.CENTER);
        PanelInduk.revalidate();
        PanelInduk.repaint();
    }


}
